name: ci
on: [push]

jobs:

  test:

    name: Test

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Setup java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '24'
        
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@02f5a82b79a547523e664fe8a7a32ea14884d7b2 # 13.6.0
        with:
          cli:  'latest'
          bb:   'latest'

      - name: Cache clojure dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
            ~/.npm
            .shadow-cljs
          key: cljdeps-${{ hashFiles('deps.edn') }}-${{ hashFiles ('package.json') }}-${{ hashFiles ('package-lock.json') }}
          restore-keys: cljdeps-

      - name: Fix git dubious directory ownership error
        run: git config --global --add safe.directory /__w/re-com/re-com

      - uses: browser-actions/setup-chrome@c785b87e244131f27c9f19c1a33e2ead956ab7ce # v1
        id: setup-chrome
        with:
          chrome-version: 811961

      - run: bb test :chrome-path '"${{ steps.setup-chrome.outputs.chrome-path }}"'

      - run: bb release-demo

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build-report
          path: target/build-report.html

      - name: Slack notification
        uses: slackapi/slack-github-action@03ea5433c137af7c0495bc0cad1af10403fc800c # v3.0.2
        if: failure() || cancelled()
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "*re-com Tests*: ${{ job.status }}\nCommit: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
            }
